.travis.yml

Adding .travis.yaml for linting helm charts

Add travis file for lint

---

ran-simulator/templates/role.yaml
ran-simulator/templates/rolebinding.yaml

Add in Role and Role binding to ran-simulator so it can change services

---

onos-gui/values.yaml
ran-simulator/templates/deployment.yaml
ran-simulator/values.yaml

This requires 
https://github.com/onosproject/ran-simulator/pull/75
to be merged first

Added in the option to disable all HO event metric in ran-simulator

---

ran-simulator/values.yaml

ran-simulator mapview: Set defaults for map scaling

---

README.md
ran-simulator/templates/NOTES.txt
sd-ran/README.md
sd-ran/requirements.yaml
sd-ran/templates/.gitignore
sd-ran/templates/NOTES.txt
sd-ran/values.yaml

Added option to install onos-config

---

onos-classic/Chart.yaml
onos-classic/requirements.yaml
onos-classic/templates/_helpers.tpl
onos-classic/templates/autoscaler.yaml
onos-classic/templates/configmap-init.yaml
onos-classic/templates/configmap-probe.yaml
onos-classic/templates/service.yaml
onos-classic/templates/statefulset.yaml
onos-classic/values.yaml

Originally located at https://github.com/opennetworkinglab/onos-kubernetes

Add helm chart for onos-classic.

---

build/bin/release

Ensure release script can support charts with dependencies that need to be updated

Update dependencies when packaging for release

---

onos-config/templates/configmap.yaml
onos-config/values.yaml
onos-ric/templates/configmap.yaml
onos-topo/templates/configmap.yaml

After we merge this, we should merge my PRs in other subsystems

Update configmaps based on changes in the logging configuration

---

onos-classic/templates/nodeports.yaml

Add optional NodePorts for services that might need to be exposed

---

onos-gui/Chart.yaml
onos-gui/values.yaml
ran-simulator/Chart.yaml
ran-simulator/values.yaml
sd-ran/templates/NOTES.txt

Updated the versions of ran-simulator and onos-gui

---

onos-classic/Chart.yaml
onos-classic/requirements.yaml

Bump onos-classic chart version.

Update Atomix dependency in onos-classic chart.

---

device-simulator/Chart.yaml
onos-classic/Chart.yaml
onos-cli/Chart.yaml
onos-cli/templates/deployment.yaml
onos-config/Chart.yaml
onos-gui/Chart.yaml
onos-topo/Chart.yaml
onos-umbrella/Chart.yaml
onos-ztp/Chart.yaml
stratum-simulator/Chart.yaml
tlaplus-monitor/Chart.yaml

It was mounted at /home/onos, but this was overwriting `.bashrc` etc

onos-cli: move mounted dir to /home/onos/config

---

dex/README.md
dex/values.yaml

starting with a minimal setup that allows requests from onos-gui (client side to follow)

Adding in the Dex Identity Provider Helm chart Fixes #124

---

onos-classic/Chart.yaml
onos-classic/templates/service.yaml
onos-classic/templates/statefulset.yaml
onos-classic/values.yaml
onos-tost/Chart.yaml
onos-tost/requirements.yaml
onos-tost/values.yaml

- Removed unused ports in TOST
- Add up4(51001) to TOST

Template service/container ports

---

onos-tost/Chart.yaml
onos-tost/templates/config.yaml
onos-tost/values.yaml

Additionally, there are a few minor refactoring:
- Improve comments
- Change naming such that it is more consistent with Stratum helm chart

[AETHER-424] Make netcfg pusher optional

---

onos-tost/Chart.yaml
onos-tost/templates/config.yaml
onos-tost/templates/configmap-config.yaml
onos-tost/values.yaml

In addition:
- Rename tost repo to tost/tost
- Minor naming consistency improvement

Support pod-config under gerrit review

---

onos-config/Chart.yaml
onos-config/templates/configmap.yaml
onos-config/values.yaml

This PR should be merged first: https://github.com/onosproject/onos-config/pull/1161 and https://github.com/onosproject/onos-config/pull/1162

Update onos-config helm chart

---

onos-umbrella/Chart.yaml

Update onos umbrella chart to use new onos-config

---

onos-umbrella/Chart.yaml
onos-umbrella/values.yaml

@ray-milkey 
You can merge this after you pushed the plugins for onos-config:v0.6.6

bumo onos-config version in onos-umbrella chart

---

onos-tost/Chart.yaml
onos-tost/templates/config.yaml
onos-tost/templates/configmap-config.yaml
onos-tost/templates/serviceaccount.yaml
onos-tost/values.yaml

- Install the serviceaccount/role/rolebinding for kubectl

Wait all pods to be running.

---

onos-umbrella/Chart.yaml
onos-umbrella/files/configs/berlin-grid-4-topo.yaml

I wanted to add relations to test out the GUI

Extend the post install job to create relations between devices

---

onos-tost/Chart.yaml
onos-tost/requirements.yaml
onos-tost/values.yaml

Upgrade to onos-classis 0.1.6 helm chart

---

onos-tost/Chart.yaml
onos-tost/templates/config.yaml
onos-tost/values.yaml

- Change the default registry secret name

Template the secret name to avoid from conflict

---

onos-classic/Chart.yaml
onos-classic/templates/statefulset.yaml

A file mounted by ConfigMap will become read-only.
Made a clone of it so Karaf can write to the file.

Make org.ops4j.pax.logging.cfg writtable

---

onos-classic/Chart.yaml
onos-tost/Chart.yaml
onos-tost/values.yaml

INT app added to default values.

tost: load INT app by default

---

onos-tost/Chart.yaml
onos-tost/requirements.yaml

- Update the TOST Helm Chart's dependency
- Target change is #223

Update tost-onos dependency

---

onos-tost/Chart.yaml
onos-tost/templates/config.yaml
onos-tost/values.yaml

- Update the default image pull policy

Update the default image tag

---

onos-classic/Chart.yaml
onos-classic/templates/configmap-init.yaml
onos-classic/templates/configmap-probe.yaml

Looks much better on ONOS UI :)

Shorten ONOS cluster ID

---

dex-ldap-umbrella/Chart.yaml
dex-ldap-umbrella/values.yaml

Changing app `aether-roc-gui` to use PKCE and code flow

dex-ldap-umbrella: Releasing 0.1.3

---

onos-operator/Chart.yaml
onos-operator/charts/config-operator/Chart.yaml
onos-operator/charts/config-operator/crds/model.yaml
onos-operator/charts/config-operator/templates/deployment.yaml
onos-operator/charts/config-operator/values.yaml
onos-operator/charts/topo-operator/Chart.yaml
onos-operator/charts/topo-operator/templates/deployment.yaml
onos-operator/charts/topo-operator/values.yaml

Integrate new CRD changes into onos-operator chart

Update onos-operator chart with new CRD changes

---

onos-umbrella/Chart.yaml
onos-umbrella/values.yaml

for updates in
* onos-cli 1.0.5
* onos-gui 1.0.4

onos-umbrella: releasing 0.1.2

---

config-models/aether-2.x/Chart.yaml
config-models/aether-2.x/files/aether-2.0.0.tree
config-models/aether-2.x/files/yang/aether-subscriber@2020-10-22.yang
config-models/aether-2.x/files/yang/connectivity-service@2020-11-30.yang
config-models/aether-2.x/files/yang/enterprise@2020-11-30.yang
config-models/aether-2.x/files/yang/qos-profile@2020-10-22.yang
config-models/aether-2.x/files/yang/security-profile@2020-11-30.yang
config-models/aether-2.x/templates/model.yaml

The YANGs were about 4 months out of date

aether-2.0.0 model - updating YANGs to latest

---

config-models/testdevice-1.x/Chart.yaml
config-models/testdevice-1.x/templates/_helpers.tpl

this allows 2 different versions of the plugin to be loaded

testdevice-1.0.0 releasing 1.0.1

---

onos-tost/Chart.yaml
onos-tost/templates/config.yaml
onos-tost/templates/configmap-config.yaml

- Moved the wait-onos logic into the loop logic

Should check ONOS's liveness before calling it

---

onos-classic/Chart.yaml
onos-classic/requirements.yaml
onos-classic/values.yaml

Update atomix dependency to use the atomix-3.1.9 release

Update atomix dependency

---

onos-tost/Chart.yaml
onos-tost/requirements.yaml

Update onos-tost charts requirements

[AETHER-1265] Integrate java profiler in TOST env

---

onos-config/Chart.yaml
onos-config/values.yaml

Do not merge until 
https://github.com/onosproject/onos-config-model/pull/33
is merged

onos-config and model-registry should use same version of onos-api

---

onos-tost/Chart.yaml
onos-tost/templates/config.yaml
onos-tost/templates/configmap-config.yaml
onos-tost/values.yaml

- Readiness is ready when ONOS cluster is ready.
- Other applications can detect ONOS cluster status by checking config pod's Ready status

Refactor the config pod to support the readiness

---

onos-tost/Chart.yaml
onos-tost/templates/config.yaml
onos-tost/templates/configmap-config.yaml

- Use the Deployment instand of the Pod for Config Pod
- Push netcfg whenever there is anything difference between ONOS config and netcfg
- Update to new image which contians jd(json differ) and gnu-sed

Check ONOS netcfg more strictly

---

onos-tost/Chart.yaml
onos-tost/values.yaml

Also remove an empty test.yaml - likely committed by accident

Enable host probing provider to support dual-homing

---

onos-config/Chart.yaml
onos-config/templates/_helpers.tpl
onos-config/templates/configmap.yaml
onos-config/templates/deployment.yaml
onos-config/values.yaml

Sidecar is disabled by default

open-config: adding OpenPolicyAgent as a sidecar

---

onos-classic/Chart.yaml
onos-classic/values.yaml

1. Previous one was manually build.
2. Use the gerrit repo [onos-classic-helm-utils](https://gerrit.opencord.org/plugins/gitiles/onos-classic-helm-utils/+/refs/heads/master) to store the dockerfile
and then automated the build/publish process by Jenkins jobs.

Replace config loader's container image.

---

onos-tost/Chart.yaml
onos-tost/values.yaml

Remove inband-telemetry from the list of the active apps

[SDFAB-432] Remove inband-telemetry

---

onos-operator/Chart.yaml
onos-operator/charts/config-operator/Chart.yaml
onos-operator/charts/config-operator/crds/model.yaml

[AETHER-2120](https://jira.opennetworking.org/browse/AETHER-2120)

AETHER-2120 add 'getStateMode' back in to 'Model' CRD

---

keycloak-389-umbrella/.gitignore
keycloak-389-umbrella/Chart.yaml
keycloak-389-umbrella/README.md
keycloak-389-umbrella/examples/README.md
keycloak-389-umbrella/examples/dsidm-commands.txt
keycloak-389-umbrella/examples/siemens-ent-admin-delete.ldif
keycloak-389-umbrella/examples/siemens-ent-admin.ldif
keycloak-389-umbrella/examples/siemens.ldif
keycloak-389-umbrella/files/keycloak/aether-roc-gui-client.json
keycloak-389-umbrella/files/keycloak/keycloak-client-scopes-groups.json
keycloak-389-umbrella/files/keycloak/keycloak-configure.sh
keycloak-389-umbrella/files/keycloak/keycloak-group-mapper.json
keycloak-389-umbrella/files/keycloak/keycloak-ldap-config.json
keycloak-389-umbrella/files/keycloak/keycloak-realm-config.json
keycloak-389-umbrella/files/keycloak/verify-ldap.json
keycloak-389-umbrella/files/ldif/aether-init.ldif
keycloak-389-umbrella/templates/NOTES.txt
keycloak-389-umbrella/templates/_helpers.tpl
keycloak-389-umbrella/templates/configmap.yaml
keycloak-389-umbrella/templates/post-install-389ds.yaml
keycloak-389-umbrella/templates/post-install-keycloak.yaml
keycloak-389-umbrella/values.yaml

Still to do:
- Add email to the 389ds schema and to sample users
- Add users to Client aether-roc-admin
- Update the upstream 389ds chart with the init command

AETHER-2125 create KeyCloak & 389 Helm Chart

---

onos-tost/Chart.yaml
onos-tost/requirements.yaml
onos-tost/values.yaml

Additionally bumps onos-classic dependency in order to be able to set resource limits for both atomix and onos

[SDFAB-554] Set resource limits for tost pods

---

Makefile
config-models/testdevice-2.x/Chart.yaml
config-models/testdevice-2.x/files/testdevice-2.0.0.tree
config-models/testdevice-2.x/files/yang/onf-test1-augmented@2020-02-29.yang
config-models/testdevice-2.x/files/yang/onf-test1-identities@2020-09-01.yang
config-models/testdevice-2.x/files/yang/onf-test1@2019-06-10.yang
config-models/testdevice-2.x/templates/model.yaml

@ray-milkey in the Makefile I have added a target `yang-lint` and added it to `make-test` - what's the best way of adding this as a `Jenkins` test dependency?

config-models: Updated TestDevice 2.0.0 YANG to pass linting

---

onos-classic/Chart.yaml
onos-classic/templates/podsecuritypolicy.yaml
onos-classic/templates/pspclusterrole.yaml
onos-classic/templates/psprolebinding.yaml
onos-classic/values.yaml

@hyunsun Please review this.
Thanks

AETHER-2600: Add PSP to onos-classic chart

---

keycloak-389-umbrella/Chart.yaml
keycloak-389-umbrella/values.yaml

389ds server startup takes a while for OpenStack VM
So increasing the sleep to around 60 secs

using sleep of 60 secs

---

config-models/stratum-1.x/Chart.yaml
config-models/stratum-1.x/README.md
onos-operator/Chart.yaml
onos-operator/charts/app-operator/Chart.yaml
onos-operator/charts/app-operator/templates/_helpers.tpl
onos-operator/charts/topo-operator/Chart.yaml
onos-umbrella/Chart.yaml
onos-umbrella/values.yaml

Also fixing image name for `config-operator-init`

Removing last reference to config.onosproject.org.Model CRD

---

onos-config/Chart.yaml
onos-umbrella/Chart.yaml

Contains ability to list all targets via gNMI get

Releasing onos-config v0.10.23

---

onos-config/Chart.yaml
onos-umbrella/Chart.yaml

This should fix the delete parent, recreate children scenario

Releasing onos-config v0.10.24

---

onos-classic/Chart.yaml
onos-classic/templates/onos-config-loader-script.yaml
onos-classic/templates/onos-config-loader.yaml
onos-classic/templates/statefulset.yaml

Adding option image pull secret to stateful set to support pulling
from a secure repo.
Adding an optional file mode for mounting volumes in onos-config-loader

Onos classic configurability

---

onos-config/Chart.yaml
onos-umbrella/Chart.yaml

the last change did not publish charts :sigh

onos-umbrella 1.3.3

---

fabric-sim/Chart.yaml
fabric-sim/templates/deployment.yaml

nodeSelector, affinity, and tolerations should be placed in Pod spec instead of Deployment spec

Fix indent of fabric-sim deployment

---

onos-config/Chart.yaml
onos-config/templates/deployment.yaml
onos-topo/Chart.yaml
onos-topo/templates/deployment.yaml
onos-umbrella/Chart.yaml

Add Atomix labels for sidecar injection to upgrade to the latest Atomix controllers.

Add labels for Atomix sidecar proxy injection

---

device-simulator/Chart.yaml
onos-cli/Chart.yaml
onos-config/Chart.yaml
onos-operator/Chart.yaml
onos-topo/Chart.yaml
onos-umbrella/Chart.yaml

We update the appVersion in the Chart.yaml file of the repositories listed below:
device-simulator
onos-cli
onos-config
onos-operator
onos-topo

bump up version
