onosproject/onos-helm-charts

onos-gui/values.yaml
The default is 5 minutes. Any stream query like ListNetworkChange will close after this timespan if there is no traffic on the stream
=> Increase grpc-web stream timeout to 1hr

sd-ran-gui/values.yaml
This temporarily removed TLS from connection between Envoy proxy and gRPC on `ran-simulator:5150`
=> Allow SD-RAN GUI to connect to ran-simulator with no TLS

onos-config/templates/deployment.yaml, onos-config/values.yaml
This provides a method for loading model plugins from Docker images as sidecars to `onos-config`
When the plugin container is loaded it copies its `.so` file to a shared folder where `onos-config` can access it as a file and load it with `-modelPlugin`. 
This is the recommended way of sharing files between sidecar containers. See https://kubernetes.io/docs/tasks/access-application-cluster/communicate-containers-same-pod-shared-volume/
Currently I am generating the model plugin Docker image in https://github.com/onosproject/config-models/pull/1
but this creates a model plugin that's incompatible with `onos-config`. I will fix this and will try to merge this then.
=> loading of ModelPlugins from docker image

tlaplus-monitor/Chart.yaml, tlaplus-monitor/README.md, tlaplus-monitor/templates/_helpers.tpl, tlaplus-monitor/templates/configmap.yaml, tlaplus-monitor/templates/deployment.yaml, tlaplus-monitor/values.yaml
This PR adds a new Helm chart to do real-time conformance monitoring with TLA+ specs using the TLC model checker. Conformance monitoring is done by consuming traces from a Kafka topic and publishing alerts (invariant violations) to another Kafka topic. Applications must write traces to a Kafka topic to be consumed by the conformance monitors.
More info in the README
=> Add Helm chart for TLA+ conformance monitoring

tlaplus-monitor/templates/configmap.yaml
Fix a bug that causes parsing issues when `'` is present in TLA+ specs
=> Allow quotations inside TLA+ modules

influxdb/README.md
You can just use the standard Helm chart with a few modifiers on the command to install.
I will do a patch for `ran-simulator` next to write "HO Metrics" out to this.
Then finally I will write something on how to link Grafana up to this.
=> Instructions on how to install Influx DB in to the cluster

tlaplus-monitor/README.md, tlaplus-monitor/templates/deployment.yaml, tlaplus-monitor/values.yaml
This PR updates the TLA+ monitoring Helm chart to use new source and sink configurations supported by https://github.com/onosproject/tlaplus-monitor/pull/3
Conformance monitoring specs can now be decoupled from the trace source and alert sink. Sources and sinks are configured by the Helm chart.
=> Update TLA+ monitoring Helm chart to use new flags

onos-ric-ho/templates/service.yaml
Add two K8s services to connect HO App with Prometheus.
One service is Cluster IP exposing 7001 port which Prometheus can access directly through domain name. The other service is NodePort exposing 33701 port for debugging. I will remove NodePort later, or make it as optional.
=> Add services to communicate with Prometheus

sd-ran-gui/templates/service.yaml
Small bugfix: Selector in Services.yaml has different `type` value compared with the `type` value in deployemet.yaml in sd-ran-gui.
To directly access Web GUI, I just added NodePort services. With that, we don't need to manually assign accessible IP address (for LoadBalancer) or manually set a port forwarding.
=> Small bugfix and add NodePort to directly access Web GUI

tlaplus-monitor/README.md, tlaplus-monitor/templates/configmap.yaml, tlaplus-monitor/templates/deployment.yaml, tlaplus-monitor/values.yaml
This PR updates the conformance monitoring chart to support sliding window configuration options introduced by https://github.com/onosproject/tlaplus-monitor/pull/6
=> Update TLA+ conformance monitor chart to support windowed model checking

onos-gui/templates/deployment.yaml, onos-gui/values.yaml
Aslo added an nginx proxy for kubernetes api
There is a GUI PR https://github.com/onosproject/onos-gui/pull/95
that is stage 1 of handling all of the services together in `onos-gui`
=> Added onos-ric and simulator services in to onos-gui services

ran-simulator/templates/deployment.yaml, ran-simulator/templates/service.yaml
The recent change to `ran-simulator`
https://github.com/onosproject/ran-simulator/pull/68
needs this env parameter - will add it to onit too
=> Added a namespace env to ran-simulator

atomix-controller/Chart.yaml, atomix-controller/crds/cluster.yaml, atomix-controller/crds/database.yaml, atomix-controller/crds/partition.yaml, atomix-controller/templates/clusterrole.yaml, atomix-controller/templates/clusterrolebinding.yaml, atomix-controller/templates/deployment.yaml, atomix-controller/templates/role.yaml, atomix-controller/templates/rolebinding.yaml, atomix-controller/templates/service.yaml, atomix-controller/templates/serviceaccount.yaml, atomix-controller/values.yaml
This PR adds a Helm chart for the Atomi controller. The chart sets up both the Atomix custom resources and deploys a controller for them. The chart supports deployment of the controller to manage resources in all namespaces or in a specific namespace, setting up permissions according to the configuration.
=> Add Helm chart for deploying the Atomix controller

atomix-controller/README.md, atomix-controller/templates/clusterrole.yaml, atomix-controller/templates/clusterrolebinding.yaml, atomix-controller/templates/deployment.yaml, atomix-controller/templates/role.yaml, atomix-controller/templates/rolebinding.yaml, atomix-controller/templates/serviceaccount.yaml, atomix-controller/values.yaml
This PR fixes a bug in the `atomix-controller` chart that did not correctly configure cluster role bindings when cluster scoped. Rather than using a `namespace` value, when the chart is configured with `scope=Cluster` it's deployed at the cluster scope, and when it's configured with `scope=Namespace` it's deployed at the namespace scope (controlling only resources within the given namespace).
=> Use 'scope' value to configure Atomix controller scope

onos-config/templates/configmap.yaml, onos-config/templates/deployment.yaml, onos-config/values.yaml, onos-ric/templates/configmap.yaml, onos-ric/templates/deployment.yaml, onos-ric/values.yaml, onos-topo/templates/configmap.yaml, onos-topo/templates/deployment.yaml, onos-topo/values.yaml
This PR adds initial support for more complex configuration of ONOS services using configuration files. Each service has a new `config` value which is an arbitrary YAML struct defined by the service. The `config` is used to populate a `ConfigMap` which is mounted to the service and can be read using the [onos-lib-go configuration functions](https://github.com/onosproject/onos-lib-go/pull/25).
=> Support configuration files in ONOS services

go.mod, go.sum, onos-ric/templates/cache.yaml, onos-ric/templates/configmap.yaml, onos-ric/templates/consensus.yaml, onos-ric/values.yaml
This PR separates the databases into two separate databases with two different consistency models. The `consensus` database is used for mastership election and related functions. The `cache` database is used to store messages.
=> Add cache database to onos-ric chart

.gitignore, build/bin/release, onos-topo/Chart.yaml
This PR adds a script to release Helm charts to GitHub pages. This branch is a work in progress. This variation of the script is untested. In order to use it, we'd need to enable GitHub Pages for this repository.
The script takes a single argument: the name of the chart to release, e.g.:
```bash
./build/bin/release onos-ric
```
=> Add script for releasing Helm charts to GitHub Pages

onos-config/templates/consensus.yaml, onos-config/tests/onos-config.go, onos-config/values.yaml, onos-ric/templates/cache.yaml, onos-ric/templates/consensus.yaml, onos-ric/templates/deployment.yaml, onos-ric/tests/onos-ric.go, onos-ric/values.yaml, onos-topo/templates/consensus.yaml, onos-topo/tests/onos-topo.go, onos-topo/values.yaml, sd-ran/requirements.yaml, sd-ran/values.yaml
This PR updates Atomix resources to use the v1beta3 API. The latest version of the Atomix API and Helm charts fix a few issues we've had with naming and deployment order.
=> Update Helm charts to use Atomix v1beta3 API

ran-simulator/templates/deployment.yaml, ran-simulator/values.yaml
Try it out with
```
helm -n micro-onos install ran-simulator ran-simulator --set image.tag=latest --set towerConfigName=berlin-honeycomb-169-6.yaml --set locationsScale=0.7
```
=> Ran-sim added a option to specify the towers config

onos-gui/Chart.yaml, onos-gui/templates/service.yaml, onos-gui/values.yaml, onos-ric-ho/Chart.yaml, onos-ric-ho/templates/service.yaml, onos-ric-ho/values.yaml, onos-ric-mlb/Chart.yaml, onos-ric-mlb/templates/service.yaml, onos-ric-mlb/values.yaml, onos-ric/templates/service.yaml, onos-ric/values.yaml, sd-ran/Chart.yaml, sd-ran/tests/sd-ran.go
Fixes a bug resulting from conflicting node ports when services are deployed concurrently in multiple namespaces.
=> Make nodePorts configurable

build/cmd/index2md/index2md.go, go.mod, go.sum
I will add it to "release" script in the next patch
Run like
```bash
go run github.com/onosproject/onos-helm-charts/build/cmd/chartsreadme > README.md
```
=> A simple tool to format the index.yaml in to a Markdown format

build/bin/release
Avoid race condition when doing multiple releases by using github's raw user content for Helm repo
=> Use raw githubusercontent for chart index updates

onos-cli/files/configs/README.md, onos-cli/files/configs/berlin-honeycomb-331-3-A-gnmi.yaml, onos-cli/files/configs/berlin-honeycomb-331-3-B-gnmi.yaml, onos-cli/files/configs/berlin-honeycomb-331-3-C-gnmi.yaml, onos-cli/files/configs/berlin-honeycomb-331-3-topo.yaml, onos-cli/files/configs/berlin-honeycomb-4-3-gnmi.yaml, onos-cli/files/configs/berlin-honeycomb-4-3-topo.yaml, onos-cli/files/configs/berlin-rectangular-4-1-gnmi.yaml, onos-cli/files/configs/berlin-rectangular-4-1-topo.yaml, onos-cli/files/configs/berlin-rectangular-9-1-gnmi.yaml, onos-cli/files/configs/berlin-rectangular-9-1-topo.yaml, onos-cli/templates/configmap.yaml, onos-cli/templates/deployment.yaml, sd-ran/templates/post-install-job.yaml, sd-ran/values.yaml
I'm lining this up so that a config can be easily loaded once the cluster has started.
Currently have to use:
```bash
onos topo load yaml berlin-honeycomb-4-3-topo.yaml
```
and then
```bash
onos config load yaml berlin-honeycomb-4-3-gnmi.yaml
```
=> onos-cli: Added some topo and config YAML files for loading

Makefile, onos-cli/Chart.yaml, ran-simulator/templates/deployment.yaml, ran-simulator/values.yaml, sd-ran/Chart.yaml, sd-ran/files/configs/README.md, sd-ran/files/configs/berlin-honeycomb-331-3-A-gnmi.yaml, sd-ran/files/configs/berlin-honeycomb-331-3-B-gnmi.yaml, sd-ran/files/configs/berlin-honeycomb-331-3-C-gnmi.yaml, sd-ran/files/configs/berlin-honeycomb-331-3-topo.yaml, sd-ran/files/configs/berlin-honeycomb-4-3-gnmi.yaml, sd-ran/files/configs/berlin-honeycomb-4-3-topo.yaml, sd-ran/templates/configmap.yaml, sd-ran/templates/post-install-job.yaml, sd-ran/values.yaml
Also fixed problem in onos-cli pod configmap
Removed unused param in ran-simulator
=> sd-ran: post install job populates onos-topo and onos-config

stratum-simulator/.helmignore, stratum-simulator/Chart.yaml, stratum-simulator/templates/_helpers.tpl, stratum-simulator/templates/deployment.yaml, stratum-simulator/templates/service.yaml, stratum-simulator/values.yaml
This PR adds a simple helm chart for stratum simulator that we can use it for ZTP.  In onit, we were exposing a service per gRPC port (I don't remember why but I think it makes more sense and easier to debug) but this one also works without adding complexity to helm chart using control flows (one service and exposes multiple gRPC ports) and perhaps in most of the cases we just need a single node scenario (i.e. --topo single). I tried to use range for service creation but it didn't work well so If I figure that out then I will update the PR.  I tested it using gNMI CLI to retrieve list of interfaces directly from the simulator. I should give it a try with onos-config as well.
=> Add a helm chart for stratum simulator

onos-ric/Chart.yaml, onos-ric/templates/service.yaml, onos-ric/templates/statefulset.yaml, sd-ran/Chart.yaml
This PR modifies the onos-ric chart to use a `StatefulSet` with a headless `Service` to enable intracluster communication within the service. The pod network identity is extracted using an init container and is propagated to peers through the Atomix controller.
This PR should not be merged until the relevant changes to onos-ric are merged. Additionally, the sd-ran chart local `file://` dependency on the onos-ric chart should be updated before the sd-ran chart is released.
=> Use StatefulSet for peer-to-peer communication in onos-ric chart

onos-tost/Chart.yaml, onos-tost/requirements.yaml, onos-tost/values.yaml
As the discussion with @charlesmcchan, we set up a new Helm Chart for the ONOS-TOST and added requirement apps as default values.
Part of atomix is used to specify the storageclass name in Kubernetes and the storageclass provider should be installed in Kubernetes advanced.
=> Add the helm chart for ONOS-TOST

onos-tost/Chart.yaml, onos-tost/requirements.yaml, onos-tost/templates/netcfg.yaml, onos-tost/values.yaml
Get netcfg from pod config repo and push it to ONOS automatically once ONOS starts.
This is a one-time task and will only be retriggered during ONOS helm reinstallation.
=> [AETHER-424] Push netcfg once ONOS is ready

onos-config/tests/onos-config.go, onos-topo/tests/onos-topo.go, onos-umbrella/tests/onos-umbrella.go
This PR implements running the ONOS chart integration tests against the published charts by adding repo URLs to the chart references.
=> Fixes to helm chart integration tests when using published charts

onos-config/Chart.yaml, onos-config/templates/deployment.yaml
To address this issue onosproject/onos-config#958 and initialize NODE_ID properly when we have a multi-node cluster.
=> Fix Node Id

onos-config/Chart.yaml, onos-config/templates/deployment.yaml
Adds a startup probe to prevent restarts while waiting for dependencies during slow startup.
=> Add startup probe to onos-config chart

onos-topo/Chart.yaml, onos-topo/templates/deployment.yaml
Adds a startup probe to prevent restarts while waiting for dependencies during slow startup.
=> Add startup probe to onos-topo chart

onos-classic/Chart.yaml, onos-classic/templates/_helpers.tpl, onos-classic/templates/configmap-logging.yaml, onos-classic/templates/statefulset.yaml, onos-classic/values.yaml
Additionally, respect ONOS_APPS to avoid `gui2` being enabled by default
=> Support custom log4j2 config and annotations via helm value

onos-config/Chart.yaml, onos-config/templates/deployment.yaml
This PR fixes a race condition in the startup of the onos-config service. If the `onos-config` container starts before model plugin containers have run, plugins may not yet have been migrated to the shared volume and onos-config startup will fail:
```
2020-09-01T22:28:36.786Z	FATAL	main	onos-config/onos-config.go:188	Unable to start onos-config plugin.Open("/usr/local/lib/shared/e2node.so.1.0.0"): realpath failed
github.com/onosproject/onos-lib-go/pkg/logging.(*zapOutput).Fatal
/go/src/github.com/onosproject/onos-config/vendor/github.com/onosproject/onos-lib-go/pkg/logging/output.go:204
github.com/onosproject/onos-lib-go/pkg/logging.(*zapLogger).Fatal
/go/src/github.com/onosproject/onos-config/vendor/github.com/onosproject/onos-lib-go/pkg/logging/logger.go:292
main.main …
```
=> Move onos-config model plugins to initContainers

onos-classic/Chart.yaml, onos-classic/requirements.yaml, onos-classic/templates/statefulset.yaml, onos-classic/values.yaml
This change allows passing of java_opts environment variable to the container through the values files, allowing for easy tuning of java parameters that ONOS uses to run
=> Passing java_opts as parameter from values.yaml

onos-topo/Chart.yaml, onos-topo/templates/_helpers.tpl, onos-topo/templates/database.yaml, onos-topo/templates/deployment.yaml, onos-topo/values.yaml
This PR adds an `image.registry` value to the onos-topo chart which optionally prefixes a Docker registry on image names. Additionally, it upgrades the default Atomix images used.
=> Add support for private Docker registries to onos-topo chart

onos-config/Chart.yaml, onos-config/templates/_helpers.tpl, onos-config/templates/database.yaml, onos-config/templates/deployment.yaml, onos-config/values.yaml
This PR adds an `image.registry` value to the onos-topo chart which optionally prefixes a Docker registry on image names. Additionally, it upgrades the default Atomix images used.
=> Add support for private Docker registries to onos-config chart

onos-classic/Chart.yaml, onos-classic/templates/configmap-probe.yaml, onos-classic/templates/statefulset.yaml, onos-classic/values.yaml
- Defines a value for the timeout
- To avoid the issue 82987 in k8s sets the timeout doubling this value
- Do not allow check-onos-status to exit immediately
- Sets a timeout for curl equals to the timeout value
- Updates chart version
- Updates imagePullPolicy for alpine image
Reference from #220 
**We can't change two charts in a single PR, so split it out from #220**
=> [AETHER-939] Fix readiness/liveness probes

onos-tost/Chart.yaml, onos-tost/templates/configmap-config.yaml, onos-tost/templates/serviceaccount.yaml, onos-tost/values.yaml
- Disable persistent volume for Atomix
We don't expect all ONOS instance going down simulteneously.
Having PV enabled doesn't provide much value under that assumption and it is known to slow down the system.
- Fixed an issue where config pusher doesn't properly wait for ONOS ready.
- Disable fabric-tofino app since we only use fabric-tna now
=> Few optimizations for ONOS clustered mode

config-models/ietf/.helmignore, config-models/ietf/Chart.yaml, config-models/ietf/files/yang/ietf-inet-types@2013-07-15.yang, config-models/ietf/files/yang/ietf-interfaces@2014-05-08.modified.yang, config-models/ietf/files/yang/ietf-yang-types@2013-07-15.yang, config-models/ietf/templates/_helpers.tpl, config-models/ietf/templates/model.yaml
This PR adds a new Helm chart defining a set of abstract YANG modules which can be used as a base for YANG models defined in other config `Model` charts.
=> Add ietf config model chart

config-models/devicesim/.helmignore, config-models/devicesim/Chart.lock, config-models/devicesim/Chart.yaml, config-models/devicesim/templates/_helpers.tpl, config-models/devicesim/templates/model.yaml
This PR adds a Helm chart defining the devicesim config model. The devicesim chart simply produces a config `Model` from the OpenConfig base model.
=> Add devicesim config model chart

onos-config/Chart.yaml, onos-config/templates/deployment.yaml, onos-config/templates/modelregistry.yaml, onos-config/values.yaml
This PR updates the onos-config chart to use the new config operator and model plugin compiler. Model plugins no longer need to be built into Docker images and defined in the onos-config chart's values. Model plugins are extensions to the onos-config API, so the onos-config chart itself doesn't need to know about them. The config operator is now responsible for compiling and loading config model plugins into onos-config pods both at startup time and runtime.
=> Migrate onos-config chart to new model plugins

onos-classic/Chart.yaml, onos-classic/templates/configmap-init.yaml, onos-classic/templates/configmap-logging.yaml, onos-classic/templates/configmap-probe.yaml, onos-classic/templates/nodeports.yaml, onos-classic/templates/service.yaml, onos-classic/templates/statefulset.yaml
The `onos-classic` app label changes with each deployment depending on `.Release.Name` this makes it hard to reference the pods using `kubectl -l app=`.
This patch sets the app label to `onos-classic` regardless of the release name for consistency.
=> Using a constant for app label

onos-config/Chart.yaml, onos-config/templates/deployment.yaml, onos-config/values.yaml
Update the onos-config chart to use the v0.4.0 compiler and use the image tag as the target version by default
=> Update onos-config chart defaults and simplify maintenance

config-models/aether-2.x/Chart.yaml, config-models/aether-2.x/templates/model.yaml
the name of the plugin should be `Aether` rather than `aether`
=> Aether-2.x - fix plugin name

Makefile, onos-umbrella/Chart.yaml, onos-umbrella/values.yaml
aether models have been moved to a private repo and are not needed here
=> onos-umbrella: releasing 0.1.9 - remove aether models

onos-cli/Chart.yaml, onos-cli/templates/deployment.yaml
tested by deploying in micro-onos environment. observed ready state on pod, and able to talk to e2t.
before change
```
Liveness:       exec [/bin/sh] delay=5s timeout=1s period=5s #success=1 #failure=3
Readiness:      exec [/bin/sh] delay=5s timeout=1s period=5s #success=1 #failure=3
Conditions:
Type              Status
Initialized       True
Ready             False
ContainersReady   False
PodScheduled      True
```
after change
```
kubectl -n micro-onos describe pod onos-cli-bdc95d65c-ztrwd
<snip>
Conditions:
Type              Status
Initialized       True
Ready             True
ContainersReady   True
PodScheduled      True
<snip>
```
```
kubectl exec -it -n micro-onos $(kubectl -n micro-onos get pods -l type=cli -o name) -- onos e2t list connections
Global ID            PLNM ID   IP …
```
=> remove liveliness probes on onos-cli

onos-tost/Chart.yaml, onos-tost/templates/config.yaml, onos-tost/templates/configmap-config.yaml
- Change the container image, we need jq and curl now
- Check the device value every 30 seconds
=> Periodically push the netcfg instead of one time push

onos-gui/Chart.yaml, onos-gui/values.yaml
Changing NodePort for `onos-gui` from **31180** to **31190** to avoid some other service that seems to have taken over **31180**
=> onos-gui: change Nodeport to 31190

.gitignore, onos-classic/Chart.yaml, onos-classic/templates/nodeports.yaml
The `selector` for the OpenFlow `nodePorts` was hardcoded to:
```
selector:
statefulset.kubernetes.io/pod-name: onos-onos-classic-{{ $index }}
```
That would only work if you install ONOS with release name `onos`.
This patch updates it to use
```
selector:
statefulset.kubernetes.io/pod-name: {{ template "fullname" $root }}-{{ $index }}
```
so that we can match the statefulset PODs regardless of the name used during the installation
=> Correctly selecting PODs for the OpenFlow NodePorts

onos-classic/Chart.yaml, onos-classic/templates/configmap-init.yaml, onos-classic/templates/configmap-logging.yaml, onos-classic/templates/configmap-probe.yaml, onos-classic/templates/nodeports.yaml, onos-classic/templates/service.yaml, onos-classic/templates/statefulset.yaml, onos-classic/values.yaml
onos-tost helm chart needs to refer to the `app_label` in the network config pusher. Making this a helm value allows us to refer to it without duplicating.
=> Use the value for app label instead of hardcode

onos-tost/Chart.yaml, onos-tost/requirements.yaml, onos-tost/values.yaml
Use the `app_label` defined in ONOS classic helm chart to correctly identify the ONOS pods.
=> Fix the label

onos-classic/Chart.yaml, onos-classic/requirements.yaml, onos-classic/templates/nodeports.yaml, onos-classic/values.yaml
Add a nodeport for each onos instance to enable the connection between client and profiler agent.
=> [AETHER-1265] Integrate Java profiler in TOST env

onos-topo/Chart.yaml, onos-topo/templates/_helpers.tpl, onos-topo/templates/configmap.yaml, onos-topo/templates/deployment.yaml, onos-topo/templates/primitives.yaml, onos-topo/templates/role.yaml, onos-topo/templates/rolebinding.yaml, onos-topo/templates/serviceaccount.yaml, onos-topo/templates/store.yaml, onos-topo/values.yaml
This PR introduces the Atomix v2beta1 API into the onos-topo chart. This is an intermediate step to migrating the chart to the v2beta1 API. This change runs two data stores -- the v1beta1 database and a v2beta1 store -- side by side, so images prior to and after the upgrade should continue to work.
This change requires that the [Atomix Kubernetes controller](https://github.com/atomix/atomix-controller) and at least one [storage plugin](https://github.com/atomix/atomix-raft-storage-plugin) be installed in the cluster:
```bash
> kubectl create -f https://raw.githubusercontent.com/atomix/atomix-controller/master/deploy/atomix-controller.yaml
> kubectl create -f https://raw.githubusercontent.com/atomix/atomix-raft-storage-plugin/master/deploy/atomix-raft-storage-plugin.yaml
```
The Atomix …
=> Add Atomix v2beta1 Store and primitives for topo store

onos-umbrella/Chart.yaml, onos-umbrella/values.yaml
Update the onos-umbrella chart to ensure onos-topo and onos-config share a single Atomix v2beta1 consensus store.
=> Update onos-config dependency to support Atomix v2beta1 API in onos-umbrella chart

dex-ldap-umbrella/Chart.yaml, dex-ldap-umbrella/README.md, dex-ldap-umbrella/templates/NOTES.txt, dex-ldap-umbrella/values.yaml
the older version would not work with Kubernetes `1.21.0`
=> dex-ldap-umbrella: upgrading to dex v2.29.0

onos-config/Chart.yaml, onos-config/values.yaml
There's something with config-model v1.0.2 that causes model plugin loading problems
=> onos-config: releasing 1.3.9 for v0.9.8 and reverting to config-model v1.0.1

keycloak-389-umbrella/Chart.yaml, keycloak-389-umbrella/values.yaml
The problem was that the `postStart` hook can be called more than once 
https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/#hook-delivery-guarantees 
Now the hook (initCommand) checks if localhost has been created already, and if not creates it
=> AETHER-2626 start up of keycloak-389-umbrella failures

onos-classic/Chart.yaml, onos-classic/templates/statefulset.yaml, onos-classic/values.yaml
as suggested here:
https://www.docker.com/blog/apache-log4j-2-cve-2021-44228/
Also this is overkill as we are building the docker image with java > 11.0.1, thus not being affected as per: https://www.lunasec.io/docs/blog/log4j-zero-day/
=> Fix: mitigate the issues identified in CVE-2021-44228 by log4j2

onos-umbrella/Chart.yaml, onos-umbrella/files/opa-rbac/devicesim-1.0.0.rego, onos-umbrella/files/opa-rbac/testdata/devicesim-1.0.0-example-get.json, onos-umbrella/templates/opa-rbac-configmap.yaml
Just a simple Open Policy Agent Rego Rules for Devicesim-1.0.0
Only `interfaces` whose `name` matches the `group`s that the user is part of will be shown
To see it in action locally do
```bash
opa eval -f pretty -b /home/scondon/go/src/github.com/onosproject/onos-helm-charts/onos-umbrella/files/opa-rbac --input /home/scondon/go/src/github.com/onosproject/onos-helm-charts/onos-umbrella/files/opa-rbac/testdata/devicesim-1.0.0-example-get.json data.devicesim_1_0_0.allowed
```
This can be done inside GoLand using the REGO plugin
=> onos-umbrella: Adding REGO rule for Devicesim-1.0.0

onos-topo/Chart.yaml, onos-topo/templates/deployment.yaml, onos-topo/values.yaml, onos-umbrella/Chart.yaml
This fixes the deprecation warning:
`spec.template.metadata.annotations[seccomp.security.alpha.kubernetes.io/pod]: deprecated since v1.19, non-functional in v1.25+; use the "seccompProfile" field instead`
=> Fix security context profile

onos-config/Chart.yaml, onos-config/templates/deployment.yaml, onos-config/values.yaml, onos-umbrella/Chart.yaml
@SeanCondon  This is the way you have in mind to enable adding prefix at runtime for each plugin? I looked at the code in config models for extracting paths and looks like you don't check the value of PREFIXED env and you just check if it is set or not. Please let me know and I finalize this PR (ignore the new plugin part, that was for my local testing).
=> Add prefix env for plugins
